import { useEffect, useState } from 'react';

const emptyRecipe = { name: '', description: '', ingredients: '', instructions: '', cuisine: '', category: 'Dinner', mealType: 'dinner', dietaryTags: '', imageUrl: '', prepTime: 15, cookTime: 20, servings: 2 };
const userId = localStorage.getItem('recipe-user-id') || crypto.randomUUID();
localStorage.setItem('recipe-user-id', userId);

function App() {
  const [recipes, setRecipes] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState('');
  const [selectedCuisine, setSelectedCuisine] = useState(''); const [selectedMealType, setSelectedMealType] = useState(''); const [selectedDietary, setSelectedDietary] = useState(''); const [selectedCategory, setSelectedCategory] = useState('');
  const [filters, setFilters] = useState({ cuisines: [], mealTypes: [], dietaryTags: [], categories: [] }); const [favoriteIds, setFavoriteIds] = useState([]); const [form, setForm] = useState(emptyRecipe); const [editingId, setEditingId] = useState(null); const [showFavorites, setShowFavorites] = useState(false);
  const headers = { 'x-user-id': userId };
  const fetchRecipes = async () => { try { const query = new URLSearchParams({ search, cuisine: selectedCuisine, mealType: selectedMealType, dietary: selectedDietary, category: selectedCategory }); const response = await fetch(`/api/recipes?${query}`); const data = await response.json(); setRecipes(data.items || []); } catch (error) { console.error(error); setRecipes([]); } finally { setLoading(false); } };
  const fetchFilters = async () => { const response = await fetch('/api/filters'); setFilters(await response.json()); };
  const fetchFavorites = async () => { const response = await fetch('/api/favorites', { headers }); const data = await response.json(); setFavoriteIds(data.ids || []); };
  useEffect(() => { fetchRecipes(); }, [search, selectedCuisine, selectedMealType, selectedDietary, selectedCategory, showFavorites]);
  useEffect(() => { fetchFilters(); fetchFavorites(); }, []);
  const visibleRecipes = showFavorites ? recipes.filter((recipe) => favoriteIds.includes(Number(recipe.id))) : recipes;
  const toggleFavorite = async (id) => { const response = await fetch(`/api/favorites/${id}/toggle`, { method: 'POST', headers }); const data = await response.json(); if (response.ok) setFavoriteIds((ids) => data.isFavorite ? [...ids, Number(id)] : ids.filter((value) => value !== Number(id))); };
  const handleSubmit = async (event) => { event.preventDefault(); const payload = { ...form, ingredients: form.ingredients.split(',').map((x) => x.trim()).filter(Boolean), instructions: form.instructions.split('\n').map((x) => x.trim()).filter(Boolean), dietaryTags: form.dietaryTags.split(',').map((x) => x.trim()).filter(Boolean), imageUrl: form.imageUrl || 'https://images.unsplash.com/photo-1495521821757-a1efb90b62d6?auto=format&fit=crop&w=900&q=80' }; const response = await fetch(`/api/recipes${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (response.ok) { setForm(emptyRecipe); setEditingId(null); fetchRecipes(); fetchFilters(); } };
  const handleEdit = (recipe) => { setEditingId(recipe.id); setForm({ ...recipe, ingredients: recipe.ingredients.join(', '), instructions: recipe.instructions.join('\n'), dietaryTags: (recipe.dietaryTags || []).join(', ') }); window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }); };
  const handleDelete = async (id) => { if (confirm('Delete this recipe?')) { await fetch(`/api/recipes/${id}`, { method: 'DELETE', headers }); fetchRecipes(); fetchFavorites(); } };
  const resetFilters = () => { setSearch(''); setSelectedCuisine(''); setSelectedMealType(''); setSelectedDietary(''); setSelectedCategory(''); };
  return <div className="app-shell">
    <header className="topbar"><div><p className="eyebrow">Healthy & tasty</p><h1>Recipe Finder</h1></div><div className="top-actions"><button className={`secondary-button ${showFavorites ? 'active' : ''}`} onClick={() => setShowFavorites(!showFavorites)}>♥ Favorites ({favoriteIds.length})</button><button className="primary-button" onClick={() => { setEditingId(null); setForm(emptyRecipe); }}>New Recipe</button></div></header>
    <section className="controls panel"><div className="search-box"><label htmlFor="search">Search recipes</label><input id="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name or ingredient" /></div><div className="filters-grid"><select value={selectedCategory} onChange={(e) => setSelectedCategory(e.target.value)}><option value="">Category</option>{filters.categories.map((x) => <option key={x}>{x}</option>)}</select><select value={selectedCuisine} onChange={(e) => setSelectedCuisine(e.target.value)}><option value="">Cuisine</option>{filters.cuisines.map((x) => <option key={x}>{x}</option>)}</select><select value={selectedMealType} onChange={(e) => setSelectedMealType(e.target.value)}><option value="">Meal type</option>{filters.mealTypes.map((x) => <option key={x}>{x}</option>)}</select><select value={selectedDietary} onChange={(e) => setSelectedDietary(e.target.value)}><option value="">Dietary</option>{filters.dietaryTags.map((x) => <option key={x}>{x}</option>)}</select><button className="secondary-button" onClick={resetFilters}>Reset</button></div></section>
    <main className="content-grid"><section className="recipes-panel"><div className="section-head"><h2>{showFavorites ? 'Favorite Recipes' : 'Recipes'}</h2><span>{visibleRecipes.length} found</span></div>{loading ? <p>Loading recipes...</p> : visibleRecipes.length === 0 ? <p className="empty-state">{showFavorites ? 'No favorites yet.' : 'No recipes match your search.'}</p> : <div className="recipe-grid">{visibleRecipes.map((recipe) => <article key={recipe.id} className="recipe-card"><img src={recipe.imageUrl} alt={recipe.name} /><div className="recipe-body"><div className="chip-row"><span className="chip">{recipe.category}</span><span className="chip">{recipe.cuisine}</span><span className="chip">{recipe.mealType}</span></div><h3>{recipe.name}</h3><p>{recipe.description}</p><ul>{recipe.ingredients.slice(0, 3).map((ingredient) => <li key={`${recipe.id}-${ingredient}`}>{ingredient}</li>)}</ul><div className="recipe-actions"><button className={`small-button favorite ${favoriteIds.includes(Number(recipe.id)) ? 'saved' : ''}`} onClick={() => toggleFavorite(recipe.id)}>{favoriteIds.includes(Number(recipe.id)) ? '♥ Saved' : '♡ Save'}</button><button className="small-button" onClick={() => handleEdit(recipe)}>Edit</button><button className="small-button danger" onClick={() => handleDelete(recipe.id)}>Delete</button></div></div></article>)}</div>}</section>
    <aside className="form-panel panel"><h2>{editingId ? 'Edit recipe' : 'Add a recipe'}</h2><form onSubmit={handleSubmit} className="recipe-form"><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows="3" /></label><label>Ingredients (comma separated)<textarea value={form.ingredients} onChange={(e) => setForm({ ...form, ingredients: e.target.value })} rows="3" required /></label><label>Instructions (one per line)<textarea value={form.instructions} onChange={(e) => setForm({ ...form, instructions: e.target.value })} rows="4" required /></label><div className="two-column"><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{['Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Snack', 'Other'].map((x) => <option key={x}>{x}</option>)}</select></label><label>Cuisine<input value={form.cuisine} onChange={(e) => setForm({ ...form, cuisine: e.target.value })} /></label></div><div className="two-column"><label>Meal Type<select value={form.mealType} onChange={(e) => setForm({ ...form, mealType: e.target.value })}><option>breakfast</option><option>lunch</option><option>dinner</option><option>dessert</option></select></label><label>Dietary Tags<input value={form.dietaryTags} onChange={(e) => setForm({ ...form, dietaryTags: e.target.value })} /></label></div><div className="two-column"><label>Prep Time<input type="number" value={form.prepTime} onChange={(e) => setForm({ ...form, prepTime: Number(e.target.value) })} /></label><label>Cook Time<input type="number" value={form.cookTime} onChange={(e) => setForm({ ...form, cookTime: Number(e.target.value) })} /></label></div><label>Image URL<input value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} /></label><div className="form-actions"><button className="primary-button">{editingId ? 'Save Changes' : 'Add Recipe'}</button>{editingId && <button type="button" className="secondary-button" onClick={() => { setEditingId(null); setForm(emptyRecipe); }}>Cancel</button>}</div></form></aside></main>
  </div>;
}
export default App;
